### ISSUE TITLE
关于商品id和基础数据

### ISSUE THREAD

**Issue by puresox** [KUD-00/resonance-helper#1]
你好，我看到readme中说商品id还未补充完，其实这些数据都是解包可以获取到的，希望对你有帮助，这是14个站点所有商品的id和基础价格等数据[https://github.com/milkory/rsns-data/blob/main/Data/HomeGoodsQuotationFactory.json](https://github.com/milkory/rsns-data/blob/main/Data/HomeGoodsQuotationFactory.json)，这个仓库里有详细的解包数据。

**Comment by KUD-00** [comment]
wow太棒了，感谢提醒，这个定义的好啊！

**Comment by KUD-00** [comment]
已经完成转移，关闭issue
#3 #2
